#!/usr/bin/env bash
# Check if script is run as root
#if [ "$EUID" -ne 0 ]
#then 
#    echo "Please run as root"
#    exit
#fi

# Ensure the nginx user exists
if ! id "nginx" &>/dev/null; then
    sudo useradd -r -M -s /sbin/nologin nginx
fi

# Modify the nginx configuration to change the user and the port

# Variables
NGINX_CONF_DIR="/etc/nginx"
NGINX_CONF_FILE="$NGINX_CONF_DIR/nginx.conf"
NGINX_DEFAULT_CONF_FILE="/etc/nginx/sites-available/default"

# change permissions so only owner of /etc/nginx/nginx.conf can do things
sudo chmod 700 $NGINX_CONF_FILE

# Set the nginx user
sudo sed -i 's/^user .*/user nginx;/' $NGINX_CONF_FILE

# Set the nginx listener port to 8080 for IPv4
sudo sed -i "s/listen [0-9]\+ default_server;/listen 8080 default_server;/" $NGINX_DEFAULT_CONF_FILE
# Set the nginx listener port to 8080 for IPv6
sudo sed -i "s/listen \[::\]:[0-9]\+ default_server;/listen [::]:8080 default_server;/" $NGINX_DEFAULT_CONF_FILE

# change owner of NGINX directories to user nginx
sudo chown root:root $NGINX_CONF_FILE

# Test the nginx configuration
if sudo nginx -t; then
    sudo -u nginx service nginx reload
else
    echo "Nginx configuration test failed"
    exit 1
fi

echo "Configuration applied successfully"
