#!/usr/bin/env bash
# scripts that takes a subdomain and a domain and displays information about it.

domain=$1

subdomain_info ()
{
    for arg
    do
        echo -n "The subdomain $arg is a "
        dig "$arg"."$domain" | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{print $4 " record and points to " $5}'
    done
}

if [ $# -eq 1 ]
then
    subdomain_info 'www' 'lb-01' 'web-01' 'web-02'
else
   subdomain=$2
   subdomain_info "$subdomain"
fi
