#!/usr/bin/env bash
# Updating package list
sudo apt update

# Installing ngix web server
sudo apt -y install nginx

# Start nginx server
sudo service nginx start

# Creating index file in /var/www/html/
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Configuring nginx to listen on port 80
sudo sed -i 's/listen [^;]*;/listen 80;/g' /etc/nginx/sites-available/default


# Reloading nginx configuration
sudo nginx -s reload

# Message if Nginx setup complete
echo "Nginx setup complete"
