#!/usr/bin/env bash
# Updating package list
sudo apt update

# Installing ngix web server
sudo apt -y install nginx

# Start nginx server
sudo service nginx start

# Creating index file in /var/www/html/
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# File path for the default Nginx configuration
FILE="/etc/nginx/sites-available/default"

# Configuring nginx to listen on port 80
#sudo sed -i 's/listen [^;]*;/listen 80;/g' $FILE

# Configuring nginx 301 redirection for '/redirect_me'
RD_ADDRESS="https://www.sirlawren.com"
# REDIRECT="/^\s*location \/ {/a \\\t\\trewrite ^\/redirect_me(.*) $RD_ADDRESS permanent;"
# sudo sed -i "$REDIRECT" $FILE
REDIRECT="location /redirect_me {\n\t\t\treturn 301 $RD_ADDRESS; \n\t}"

#sudo sed -i "/^\t}/a \\\n\t$REDIRECT" $FILE
##sudo sed -i "/server_name _;/a \\\n\t$REDIRECT" $FILE
sudo sed -i ":a;N;\$!ba;s|\(location [^{}]*{\)[^{}]*\}|$REDIRECT|1" $FILE

# Reloading nginx configuration
#sudo nginx -s reload
sudo service nginx restart

# Message if Nginx setup complete
#echo "Nginx setup complete"
