#!/usr/bin/env bash
# Updating package list
sudo apt update

# Installing ngix web server
sudo apt -y install nginx

# Start nginx server
sudo service nginx start

# Creating index file in /var/www/html/
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# File path for the default Nginx configuration
FILE="/etc/nginx/sites-available/default"

# Configuring nginx to listen on port 80
sudo sed -i 's/listen [^;]*;/listen 80;/g' $FILE

# Configuring nginx to redirect '/redirect_me'
RD_ADDRESS="https://www.sirlawren.com"
REDIRECT="location /redirect_me {\\n\\t\\treturn 301 $RD_ADDRESS; \\n\\t}"

sudo sed -i "/^\s*server {/a \\\t$REDIRECT" $FILE
# Reloading nginx configuration
sudo nginx -s reload

# Message if Nginx setup complete
echo "Nginx setup complete"
