#!/usr/bin/env bash
# Updating package list
sudo apt update

# Installing ngix web server
sudo apt -y install nginx

# Start nginx server
sudo service nginx start

# Creating index file in /var/www/html/
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Creating a custom 404 page in /var/www/html/
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

# File path for the default Nginx configuration
FILE="/etc/nginx/sites-available/default"

# Configuring nginx to listen on port 80
#sudo sed -i 's/listen [^;]*;/listen 80;/g' $FILE

# Configuring nginx to redirect '/redirect_me'
#RD_ADDRESS="https://www.sirlawren.com"
#REDIRECT="location /redirect_me {\\n\\t\\treturn 301 $RD_ADDRESS; \\n\\t}"

#sudo sed -i "/^\s*server {/a \\\t$REDIRECT" $FILE

# Setting up the custom 404 page in the Nginx default configuration
CUSTOM_404_CONFIG="error_page 404 /404.html; \\n\\tlocation = /var/www/html/404.html { \\n\\tinternal; \\n\\t}"

# Inserting the custom 404 config into the Nginx default config
sudo sed -i "/^\s*server {/a \\\t$CUSTOM_404_CONFIG" $FILE


# Reloading nginx configuration
sudo nginx -s reload

# Message if Nginx setup complete
echo "Nginx setup complete"
