#!/usr/bin/env bash
# Updating package list
sudo apt update

# Installing ngix web server
sudo apt -y install nginx

# Start nginx server
sudo service nginx start

# Creating index file in /var/www/html/
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Create a custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null

# File path for the default Nginx configuration
FILE="/etc/nginx/sites-available/default"

# Configuring nginx to listen on port 80
sudo sed -i 's/listen [^;]*;/listen 80;/g' $FILE

# Configuring nginx to redirect '/redirect_me'
RD_ADDRESS="https://www.sirlawren.com"
REDIRECT="/^\s*location \/ {/a \\\t\\trewrite ^\/redirect_me(.*) $RD_ADDRESS permanent;"
sudo sed -i "$REDIRECT" $FILE

# Configure Nginx to use this page for 404 errors
ERROR_PAGE="error_page 404 \/custom_404.html;"
sudo sed -i "/server {/a \\\t$ERROR_PAGE" $FILE

# Configure the custom 404 page to be internally accessible only
INTERNAL_404="location = \/custom_404.html {\\\n\\tinternal;\\\n}"
sudo sed -i "/error_page 404 \/custom_404.html;/a $INTERNAL_404" $FILE

# Reloading nginx configuration
sudo nginx -s reload

# Message if Nginx setup complete
echo "Nginx setup complete"
