#!/usr/bin/env bash
#script to make a MySQL backup

# Check if a password is provided
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <MySQL root password>"
    exit 1
fi

# MySQL user and password
USER="root"
PASSWORD="$1"

if ! mysqldump -u "$USER" -p"$PASSWORD" --all-databases > backup.sql; then
    echo "MySQL dump failed!"
    exit 1
fi

# Compress the SQL dump to tar.gz with the required format
DATE_FORMAT=$(date +"%d-%m-%Y")

if tar -czvf "${DATE_FORMAT}.tar.gz" backup.sql; then
    echo "Backup was successfully created: ${DATE_FORMAT}.tar.gz"
else
    echo "Failed to create the compressed backup."
fi

# Optionally, clean up by removing the backup.sql file
##rm -f backup.sql
