#!/usr/bin/env bash
# Displaying the content of the file /etc/passwd, (username user id, Home directory path for the user)
file="/etc/passwd"
while IFS=: read -r username password uid gid uid_info homedir cmd_shell;
do
	echo "The user $username is part of the $gid gang, lives in $homedir: and rides $cmd_shell. $uid's place is protected by the passcode $password, more info about the user here: $uid_info"
done < "$file"
