#!/usr/bin/env bash
# Displaying parsed Apache logs in list format: Group visitors by IP and HTTP status code, show number of occurrences and sort the list
awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
