#!/usr/bin/env bash
# Displaying "Best School" 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
i=1
while [ $i -lt 11 ]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$((i+1));
done
