#!/usr/bin/env bash
# Displaying numbers from 1 to 20 and bad luck from China after 4, bad luck from Japan after 9 & bad luck from Italy after 17.
i=1
while [ $i -lt 21 ]
do
	echo $i

	if [ $i -eq 4 ]
	then
		echo "bad luck from China"
	elif [ $i -eq 9 ]
	then
		echo "bad luck from Japan"
	elif [ $i -eq 17 ]
	then
		echo "bad luck from Italy"
	fi
	i=$((i+1));
done
