#!/usr/bin/env bash
# script to run Nginx with nginx user.
sed -i 's/# www-data/user nginx/g' /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
