#!/usr/bin/env bash
# script to run Nginx with nginx user.
sed -i 's/listen [^;]*;/listen 8080 default_server;/g' /etc/nginx/sites-available/default
sed -i "s/#user www-data/user nginx/g" /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
pkill apache2
su - nginx service nginx restart
