#!/usr/bin/env bash
# script to run Nginx with nginx user.
sed -i "s/#user www-data/user nginx/g" /etc/nginx/nginx.conf
sed -i 's/listen [^;]*;/listen 8080;/g' /etc/nginx/sites-available/default
chmod 600 /etc/nginx/nginx.conf
pkill apache2
su - nginx service nginx restart
